package auth

import "tuya-ipc-terminal/pkg/tuya"

type CountryCode struct {
	A         string `json:"a"`         // ISO country code (e.g., "DE")
	C         string `json:"c"`         // Phone country code (e.g., "49")
	Continent string `json:"continent"` // Continent code
	ISO3      string `json:"iso3"`      // ISO3 code
	N         string `json:"n"`         // Country name
}

var AvailableRegions = []tuya.Region{
	{"eu-central", "protect-eu.ismartlife.me", "Central Europe", "EU"},
	{"eu-east", "protect-we.ismartlife.me", "East Europe", "EU"},
	{"us-west", "protect-us.ismartlife.me", "West America", "AZ"},
	{"us-east", "protect-ue.ismartlife.me", "East America", "AZ"},
	{"china", "protect.ismartlife.me", "China", "AY"},
	{"india", "protect-in.ismartlife.me", "India", "IN"},
}

var CountryCodesData = []CountryCode{
	{"AD", "376", "EU", "AND", "Andorra"},
	{"AE", "971", "AS", "ARE", "United Arab Emirates"},
	{"AF", "93", "AS", "AFG", "Afghanistan"},
	{"AG", "1268", "NA", "ATG", "Antigua and Barbuda"},
	{"AI", "1264", "NA", "AIA", "Anguilla"},
	{"AL", "355", "EU", "ALB", "Albania"},
	{"AM", "374", "AS", "ARM", "Armenia"},
	{"AO", "244", "AF", "AGO", "Angola"},
	{"AR", "54", "SA", "ARG", "Argentina"},
	{"AS", "1684", "OC", "ASM", "American Samoa"},
	{"AT", "43", "EU", "AUT", "Austria"},
	{"AU", "61", "OC", "AUS", "Australia"},
	{"AW", "297", "NA", "ABW", "Aruba"},
	{"AX", "35818", "EU", "ALA", "Oran"},
	{"AZ", "994", "AS", "AZE", "Azerbaijan"},
	{"BA", "387", "EU", "BIH", "Bosnia and Herzegovina"},
	{"BB", "1246", "NA", "BRB", "Barbados"},
	{"BD", "880", "AS", "BGD", "Bangladesh"},
	{"BE", "32", "EU", "BEL", "Belgium"},
	{"BF", "226", "AF", "BFA", "Burkina Faso"},
	{"BG", "359", "EU", "BGR", "Bulgaria"},
	{"BH", "973", "AS", "BHR", "Bahrain"},
	{"BI", "257", "AF", "BDI", "Burundi"},
	{"BJ", "229", "AF", "BEN", "Benin"},
	{"BL", "590", "NA", "BLM", "St. Barthelemy"},
	{"BM", "1441", "NA", "BMU", "Bermuda"},
	{"BN", "673", "AS", "BRN", "Brunei"},
	{"BO", "591", "SA", "BOL", "Bolivia"},
	{"BQ", "535", "EU", "BES", "Dutch Caribbean"},
	{"BR", "55", "SA", "BRA", "Brazil"},
	{"BS", "1242", "NA", "BHS", "Bahamas"},
	{"BT", "975", "AS", "BTN", "Bhutan"},
	{"BW", "267", "AF", "BWA", "Botswana"},
	{"BY", "375", "EU", "BLR", "Belarus"},
	{"BZ", "501", "NA", "BLZ", "Belize"},
	{"CA", "1", "NA", "CAN", "Canada"},
	{"CD", "243", "AF", "COD", "Democratic Republic of the Congo"},
	{"CF", "236", "AF", "CAF", "Central African Republic"},
	{"CG", "242", "AF", "COG", "Republic of the Congo"},
	{"CH", "41", "EU", "CHE", "Switzerland"},
	{"CI", "225", "AF", "CIV", "Ivory Coast"},
	{"CK", "682", "OC", "COK", "Cook Islands"},
	{"CL", "56", "SA", "CHL", "Chile"},
	{"CM", "237", "AF", "CMR", "Cameroon"},
	{"CN", "86", "AS", "CHN", "China"},
	{"CO", "57", "SA", "COL", "Colombia"},
	{"CR", "506", "NA", "CRI", "Costa Rica"},
	{"CV", "238", "AF", "CPV", "Cape Verde"},
	{"CW", "5999", "NA", "CUW", "Curacao"},
	{"CY", "357", "AS", "CYP", "Cyprus"},
	{"CZ", "420", "EU", "CZE", "Czech Republic"},
	{"DE", "49", "EU", "DEU", "Germany"},
	{"DJ", "253", "AF", "DJI", "Djibouti"},
	{"DK", "45", "EU", "DNK", "Denmark"},
	{"DM", "1767", "NA", "DMA", "Dominica"},
	{"DO", "1809", "NA", "DOM", "Dominican Republic (1-809)"},
	{"DZ", "213", "AF", "DZA", "Algeria"},
	{"EC", "593", "SA", "ECU", "Ecuador"},
	{"EE", "372", "EU", "EST", "Estonia"},
	{"EG", "20", "AF", "EGY", "Egypt"},
	{"ER", "291", "AF", "ERI", "Eritrea"},
	{"ES", "34", "EU", "ESP", "Spain"},
	{"ET", "251", "AF", "ETH", "Ethiopia"},
	{"FI", "358", "EU", "FIN", "Finland"},
	{"FJ", "679", "OC", "FJI", "Fiji"},
	{"FK", "500", "SA", "FLK", "Falkland Islands"},
	{"FM", "691", "OC", "FSM", "Federated States of Micronesia"},
	{"FO", "298", "EU", "FRO", "Faroe Islands"},
	{"FR", "33", "EU", "FRA", "France"},
	{"GA", "241", "AF", "GAB", "Gabon"},
	{"GB", "44", "EU", "GBR", "United Kingdom"},
	{"GD", "1473", "NA", "GRD", "Grenada"},
	{"GE", "995", "AS", "GEO", "Georgia"},
	{"GF", "594", "SA", "GUF", "French Guiana"},
	{"GH", "233", "AF", "GHA", "Ghana"},
	{"GI", "350", "EU", "GIB", "Gibraltar"},
	{"GL", "299", "NA", "GRL", "Greenland"},
	{"GM", "220", "AF", "GMB", "Gambia"},
	{"GN", "224", "AF", "GIN", "Guinea"},
	{"GP", "590", "NA", "GLP", "Guadeloupe"},
	{"GQ", "240", "AF", "GNQ", "Equatorial Guinea"},
	{"GR", "30", "EU", "GRC", "Greece"},
	{"GT", "502", "NA", "GTM", "Guatemala"},
	{"GU", "1671", "OC", "GUM", "Guam"},
	{"GW", "245", "AF", "GNB", "Guinea-Bissau"},
	{"GY", "592", "SA", "GUY", "Guyana"},
	{"HK", "852", "AS", "HKG", "Hong Kong SAR (China)"},
	{"HN", "504", "NA", "HND", "Honduras"},
	{"HR", "385", "EU", "HRV", "Croatia"},
	{"HT", "509", "NA", "HTI", "Haiti"},
	{"HU", "36", "EU", "HUN", "Hungary"},
	{"ID", "62", "AS", "IDN", "Indonesia"},
	{"IE", "353", "EU", "IRL", "Ireland"},
	{"IL", "972", "AS", "ISR", "Israel"},
	{"IM", "44", "EU", "IMN", "Isle of Man"},
	{"IN", "91", "AS", "IND", "India"},
	{"IO", "246", "AS", "IOT", "British Indian Ocean Territory"},
	{"IQ", "964", "AS", "IRQ", "Iraq"},
	{"IS", "354", "EU", "ISL", "Iceland"},
	{"IT", "39", "EU", "ITA", "Italy"},
	{"JM", "1876", "NA", "JAM", "Jamaica"},
	{"JO", "962", "AS", "JOR", "Jordan"},
	{"JP", "81", "AS", "JPN", "Japan"},
	{"KE", "254", "AF", "KEN", "Kenya"},
	{"KG", "996", "AS", "KGZ", "Kyrgyzstan"},
	{"KH", "855", "AS", "KHM", "Cambodia"},
	{"KI", "686", "OC", "KIR", "Kiribati"},
	{"KM", "269", "AF", "COM", "Comoros"},
	{"KN", "1869", "NA", "KNA", "Saint Kitts and Nevis"},
	{"KR", "82", "AS", "KOR", "South Korea"},
	{"KW", "965", "AS", "KWT", "Kuwait"},
	{"KY", "1345", "NA", "CYM", "Cayman Islands"},
	{"KZ", "7", "AS", "KAZ", "Kazakstan"},
	{"LA", "856", "AS", "LAO", "Laos"},
	{"LB", "961", "AS", "LBN", "Lebanon"},
	{"LC", "1758", "NA", "LCA", "Saint Lucia"},
	{"LI", "423", "EU", "LIE", "Liechtenstein"},
	{"LK", "94", "AS", "LKA", "Sri Lanka"},
	{"LR", "231", "AF", "LBR", "Liberia"},
	{"LS", "266", "AF", "LSO", "Lesotho"},
	{"LT", "370", "EU", "LTU", "Lithuania"},
	{"LU", "352", "EU", "LUX", "Luxembourg"},
	{"LV", "371", "EU", "LVA", "Latvia"},
	{"LY", "218", "AF", "LBY", "Libya"},
	{"MA", "212", "AF", "MAR", "Morocco"},
	{"MC", "377", "EU", "MCO", "Monaco"},
	{"MD", "373", "EU", "MDA", "Moldova"},
	{"ME", "382", "EU", "MNE", "Montenegro"},
	{"MF", "590", "NA", "MAF", "French Saint Martin"},
	{"MG", "261", "AF", "MDG", "Madagascar"},
	{"MH", "692", "OC", "MHL", "Marshall Islands"},
	{"MK", "389", "EU", "MKD", "Republic of North Macedonia"},
	{"ML", "223", "AF", "MLI", "Mali"},
	{"MM", "95", "AS", "MMR", "Myanmar (Burma)"},
	{"MN", "976", "AS", "MNG", "Mongolia"},
	{"MO", "853", "AS", "MAC", "Macau SAR (China)"},
	{"MP", "1670", "OC", "MNP", "Northern Mariana Islands"},
	{"MQ", "596", "NA", "MTQ", "Martinique"},
	{"MR", "222", "AF", "MRT", "Mauritania"},
	{"MS", "1664", "NA", "MSR", "Montserrat"},
	{"MT", "356", "EU", "MLT", "Malta"},
	{"MU", "230", "AF", "MUS", "Mauritius"},
	{"MV", "960", "AS", "MDV", "Maldives"},
	{"MW", "265", "AF", "MWI", "Malawi"},
	{"MX", "52", "NA", "MEX", "Mexico"},
	{"MY", "60", "AS", "MYS", "Malaysia"},
	{"MZ", "258", "AF", "MOZ", "Mozambique"},
	{"NA", "264", "AF", "NAM", "Namibia"},
	{"NCL", "687", "OC", "NCL", "New Caledonia"},
	{"NE", "227", "AF", "NER", "Niger"},
	{"NF", "672", "OC", "NFK", "Norfolk Island"},
	{"NG", "234", "AF", "NGA", "Nigeria"},
	{"NI", "505", "NA", "NIC", "Nicaragua"},
	{"NL", "31", "EU", "NLD", "Netherlands"},
	{"NO", "47", "EU", "NOR", "Norway"},
	{"NP", "977", "AS", "NPL", "Nepal"},
	{"NR", "674", "OC", "NRU", "Nauru"},
	{"NU", "683", "OC", "NIU", "Niue"},
	{"NZ", "64", "OC", "NZL", "New Zealand"},
	{"OM", "968", "AS", "OMN", "Oman"},
	{"PA", "507", "NA", "PAN", "Panama"},
	{"PE", "51", "SA", "PER", "Peru"},
	{"PF", "689", "OC", "PYF", "French Polynesia"},
	{"PG", "675", "OC", "PNG", "Papua New Guinea"},
	{"PH", "63", "AS", "PHL", "Philippines"},
	{"PK", "92", "AS", "PAK", "Pakistan"},
	{"PL", "48", "EU", "POL", "Poland"},
	{"PM", "508", "NA", "SPM", "Saint Pierre and Miquelon"},
	{"PR", "1787", "NA", "PRI", "Puerto Rico"},
	{"PS", "970", "AS", "PSE", "Palestine"},
	{"PT", "351", "EU", "PRT", "Portugal"},
	{"PW", "680", "OC", "PLW", "Palau"},
	{"PY", "595", "SA", "PRY", "Paraguay"},
	{"QA", "974", "AS", "QAT", "Qatar"},
	{"RE", "262", "AF", "REU", "Reunion"},
	{"RO", "40", "EU", "ROU", "Romania"},
	{"RS", "381", "EU", "SRB", "Serbia"},
	{"RU", "7", "EU", "RUS", "Russia"},
	{"RW", "250", "AF", "RWA", "Rwanda"},
	{"SA", "966", "AS", "SAU", "Saudi Arabia"},
	{"SB", "677", "OC", "SLB", "Solomon Islands"},
	{"SC", "248", "AF", "SYC", "Seychelles"},
	{"SE", "46", "EU", "SWE", "Sweden"},
	{"SG", "65", "AS", "SGP", "Singapore"},
	{"SI", "386", "EU", "SVN", "Slovenia"},
	{"SJ", "4779", "EU", "SJM", "Svalbard and Jan Mayen"},
	{"SK", "421", "EU", "SVK", "Slovakia"},
	{"SL", "232", "AF", "SLE", "Sierra Leone"},
	{"SM", "378", "EU", "SMR", "San Marino"},
	{"SN", "221", "AF", "SEN", "Senegal"},
	{"SO", "252", "AF", "SOM", "Somalia"},
	{"SR", "597", "SA", "SUR", "Suriname"},
	{"ST", "239", "AF", "STP", "Sao Tome and Principe"},
	{"SV", "503", "NA", "SLV", "El Salvador"},
	{"SX", "1721", "NA", "SXM", "Sint Maarten"},
	{"SZ", "268", "AF", "SWZ", "Swaziland"},
	{"TC", "1649", "NA", "TCA", "Turks and Caicos Islands"},
	{"TD", "235", "AF", "TCD", "Chad"},
	{"TG", "228", "AF", "TGO", "Togo"},
	{"TH", "66", "AS", "THA", "Thailand"},
	{"TJ", "992", "AS", "TJK", "Tajikistan"},
	{"TK", "690", "OC", "TKL", "Tokelau"},
	{"TL", "670", "AS", "TLS", "East Timor"},
	{"TM", "993", "AS", "TKM", "Turkmenistan"},
	{"TN", "216", "AF", "TUN", "Tunisia"},
	{"TO", "676", "OC", "TON", "Tonga"},
	{"TR", "90", "AS", "TUR", "Turkey"},
	{"TT", "1868", "NA", "TTO", "Trinidad and Tobago"},
	{"TV", "688", "OC", "TUV", "Tuvalu"},
	{"TW", "886", "AS", "TWN", "Taiwan (China)"},
	{"TZ", "255", "AF", "TZA", "Tanzania"},
	{"UA", "380", "EU", "UKR", "Ukraine"},
	{"UG", "256", "AF", "UGA", "Uganda"},
	{"US", "1", "NA", "USA", "United States of America"},
	{"UY", "598", "SA", "URY", "Uruguay"},
	{"UZ", "998", "AS", "UZB", "Uzbekistan"},
	{"VA", "379", "EU", "VAT", "Vatican"},
	{"VC", "1784", "NA", "VCT", "Saint Vincent and the Grenadines"},
	{"VE", "58", "SA", "VEN", "Venezuela"},
	{"VG", "1284", "NA", "VGB", "British Virgin Islands"},
	{"VI", "1340", "NA", "VIR", "U.S. Virgin Islands"},
	{"VN", "84", "AS", "VNM", "Vietnam"},
	{"VU", "678", "OC", "VUT", "Vanuatu"},
	{"WF", "681", "OC", "WLF", "Wallis and Futuna"},
	{"WS", "685", "OC", "WSM", "Samoa"},
	{"YE", "967", "AS", "YEM", "Yemen"},
	{"YT", "262", "AF", "MYT", "Mayotte"},
	{"ZA", "27", "AF", "ZAF", "South Africa"},
	{"ZM", "260", "AF", "ZMB", "Zambia"},
	{"ZW", "263", "AF", "ZWE", "Zimbabwe"},
}
