name: "Philips Avent WebRTC Bridge"
description: "WebRTC to RTSP bridge for Philips Avent baby monitors"
version: "2026.4.4-rc6"
slug: "aventproxy_bridge"
image: "ghcr.io/thekoma/aventproxy-bridge"
url: "https://github.com/thekoma/aventproxy"
arch:
  - amd64
  - aarch64
host_network: true
options:
  cameras: []
schema:
  signing_key: str?
  sid: str?
  ecode: str?
  partner: str?
  app_key: str?
  device_id: str?
  package_name: str?
  cameras:
    - camera_id: str?
      camera_name: str?
startup: "application"
boot: "auto"
environment:
  WAIT_FOR_CONFIG: "true"
map:
  - config:rw
